### ISSUE TITLE
APR calculation instructions innacurate since withdrawals?

### ISSUE THREAD

**Issue by MeLlamoPablo** [lidofinance/docs#208]
Hello. I believe the ["Add calculation of staker rewards APR"](https://github.com/lidofinance/docs/blob/1c13cd87ff54acbb7105826fab7bacb435d09708/docs/contracts/lido-oracle.md#add-calculation-of-staker-rewards-apr) section of the `LidoOracle` contract page is out of date.

The latest report given by [`LidoOracle#getLastCompletedReportDelta`
](https://etherscan.io/address/0x442af784A788A5bd6F42A01Ebe9F287a871243fb#readProxyContract) is:

```
postTotalPooledEther: 6711436.779126918302447177 ETH
preTotalPooledEther: 6721680.547593358725697807 ETH
timeElapsed: 86388 seconds
```

As you can see, the pre-Ether is higher than the post-Ether. Using the formula described on the article:

```
protocolAPR = (postTotalPooledEther - preTotalPooledEther) * secondsInYear / (preTotalPooledEther * timeElapsed)
lidoFeeAsFraction = lidoFee / basisPoint
userAPR = protocolAPR * (1 - lidoFeeAsFraction)
```

yields around -50% APR, which is incorrect. The note states that post/pre is collected instead of current/last to avoid new ETH staked influencing the results. But it seems like ETH withdrawn does have an influence over it.

Should the docs be updated to reflect this? Or am I missing something?

**Comment by TheDZhon** [comment]
Thank you for raising this question :+1: 

We are updating the docs, yet not many of them are presented.

Please refer to the recently published guide:
https://docs.lido.fi/integrations/api#lido-apr

**Comment by MeLlamoPablo** [comment]
Thanks for your quick answer. This works for us :) Closing this issue if you don't mind
